### ISSUE TITLE
Not being able to use the submodule 'morphology'

### ISSUE THREAD

**Issue by abdullah-alnahas** [obulat/trLemmer#3]
Hello,
I need to generate all possible morphological analyses of all words in a sentence. I see that's already implemented in the submodule `morphology.py`. It can be used as:
`trLemmer.morphology.MorphAnalyzer().analyze_sentence(sentence)`
However, the submodule `morphology` is not `import`able. One can import it if `__init__.py` became something like this:
```
# -*- coding: utf-8 -*-

"""Top-level package for Turkish Lemmatizer."""

__author__ = """Olga Bulat"""
__email__ = 'obulat@gmail.com'
__version__ = '0.1.0'

from .trLemmer import TrLemmer
from . import morphology

__all__ = ['TrLemmer', 'morphology']
```
Is `morphology` already `import`able in a way that I didn't manage to?
If not, are you planning to expose the submodule 'morphology'?

Thanks.

**Comment by obulat** [comment]
Thank you for the issue, it made me return to the project :)

Actually, as this is my first project of this size, I was just trying to figure out the project structure, so I added a `trLemmer.py` module, which turned out unnecessary. So, now I removed it, added a new result type so that results now are easier to use, turned off logging, and added some examples.

I must warn that this project is in pre-alpha stage, so you are free to use it, fork it and change it as you wish, but it's not ready to be used in production, and will be changed a lot.
I've read excellent documentation of pymorphy2.py in Russian, and plan to change the api/ documentation of this project based on that.
